# -*- coding: utf-8 -*-
"""Generate colorr's R sources from the assembled palette tables."""
import json, os, textwrap

PKG = "/Users/f00421k/Documents/GitHub/colorr"
cur = json.load(open('current.json'))
leg = json.load(open('legacy.json'))

SOCCER = ["epl", "laliga", "seriea", "bundesliga", "ligue1", "mls"]
LEAGUE_LABEL = {
    "epl": "English Premier League", "laliga": "LaLiga", "seriea": "Serie A",
    "bundesliga": "Bundesliga", "ligue1": "Ligue 1", "mls": "Major League Soccer",
    "mlb": "Major League Baseball", "nba": "National Basketball Association",
    "wnba": "Women's National Basketball Association",
    "nfl": "National Football League", "nhl": "National Hockey League",
}
ORDER = ["epl", "laliga", "seriea", "bundesliga", "ligue1", "mls",
         "mlb", "nba", "wnba", "nfl", "nhl"]

def r_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def pal_lit(colors, indent):
    pad = " " * indent
    items = []
    for i, (nm, hx) in enumerate(colors):
        items.append(f'{r_str(nm)} = {r_str(hx)}' if nm else r_str(hx))
    if not items:
        return "character(0)"
    body = (",\n" + pad).join(items)
    return "c(" + body + ")"

def league_block(name, teams, indent=2):
    pad = " " * indent
    out = [f"{pad}{name} = list("]
    keys = sorted(teams)
    for i, k in enumerate(keys):
        t = teams[k]
        cols = t["colors"] if isinstance(t, dict) else t
        label = t["name"] if isinstance(t, dict) else None
        lit = pal_lit(cols, indent + 2 + len(k) + 5)
        comma = "," if i < len(keys) - 1 else ""
        cmt = f"  # {label}" if label else ""
        out.append(f"{pad}  {k} = {lit}{comma}{cmt}")
    out.append(f"{pad})")
    return "\n".join(out)

# ---------------------------------------------------------------- palettes
hdr = ("# Generated by data-raw/build_palettes.py -- do not edit by hand.\n"
       "# Sources are listed in data-raw/provenance.json and in the package README.\n\n")

blocks = [league_block(lg, cur[lg]) for lg in ORDER]
open(os.path.join(PKG, "R", "palettes-current.R"), "w").write(
    hdr + "#' @noRd\n.colorr_palettes <- list(\n" + ",\n\n".join(blocks) + "\n)\n")

lblocks = [league_block(lg, leg[lg]) for lg in ["epl", "mlb", "nba", "nfl", "nhl"]]
open(os.path.join(PKG, "R", "palettes-legacy.R"), "w").write(
    "# Generated by data-raw/build_palettes.py -- do not edit by hand.\n"
    "# The colorr 1.0.1 palettes, kept so old code and old-season figures still reproduce.\n\n"
    "#' @noRd\n.colorr_legacy <- list(\n" + ",\n\n".join(lblocks) + "\n)\n")

# ---------------------------------------------------------------- metadata
meta = ["# Generated by data-raw/build_palettes.py -- do not edit by hand.\n",
        "#' @noRd", ".colorr_leagues_meta <- list("]
for i, lg in enumerate(ORDER):
    comma = "," if i < len(ORDER) - 1 else ""
    meta.append(f'  {lg} = list(label = {r_str(LEAGUE_LABEL[lg])}, '
                f'soccer = {"TRUE" if lg in SOCCER else "FALSE"}){comma}')
meta.append(")\n")
open(os.path.join(PKG, "R", "leagues.R"), "w").write("\n".join(meta))

# ---------------------------------------------------------------- choices
def choices_vec(keys, indent):
    pad = " " * indent
    line, lines = "", []
    for k in keys:
        piece = r_str(k) + ", "
        if len(line) + len(piece) > 92:
            lines.append(line.rstrip()); line = ""
        line += piece
    lines.append(line.rstrip().rstrip(","))
    return ("\n" + pad).join(lines)

json.dump({lg: sorted(cur[lg]) for lg in ORDER}, open('choices.json', 'w'), indent=1)
soccer_keys = sorted(k for lg in SOCCER for k in cur[lg])
json.dump(soccer_keys, open('soccer_keys.json', 'w'), indent=1)
print("wrote palettes-current.R, palettes-legacy.R, leagues.R")
print({lg: len(cur[lg]) for lg in ORDER}, "soccer:", len(soccer_keys))
