# key = R-facing team key ; value = (Display Name, teamcolorcodes slug or None)
EPL = {
 "arsenal":("Arsenal","arsenal-color-codes"),
 "aston_villa":("Aston Villa","aston-villa-fc-color-codes"),
 "bournemouth":("AFC Bournemouth","afc-bournemouth-color-codes"),
 "brentford":("Brentford",None),
 "brighton":("Brighton & Hove Albion","brighton-hove-albion-colors"),
 "chelsea":("Chelsea","chelsea-color-codes"),
 "coventry_city":("Coventry City","coventry-city-f-c-color-codes"),
 "crystal_palace":("Crystal Palace","crystal-palace-fc-colors"),
 "everton":("Everton","everton-fc-colors"),
 "fulham":("Fulham","fulham-fc-color-codes"),
 "hull":("Hull City","hull-city-a-f-c-color-codes"),
 "ipswich_town":("Ipswich Town",None),
 "leeds_united":("Leeds United","leeds-united-football-club-colors"),
 "liverpool":("Liverpool","liverpool-fc-colors"),
 "man_city":("Manchester City","manchester-city-fc-colors"),
 "man_united":("Manchester United","manchester-united-colors"),
 "newcastle":("Newcastle United","newcastle-united-fc-colors"),
 "nottingham_forest":("Nottingham Forest","nottingham-forest-f-c-color-codes"),
 "sunderland":("Sunderland",None),
 "tottenham":("Tottenham Hotspur","tottenham-hotspur-colors"),
}
LALIGA = {
 "alaves":("Deportivo Alavés","deportivo-alaves-color-codes"),
 "athletic_bilbao":("Athletic Bilbao","athletic-bilbao-color-codes"),
 "atletico_madrid":("Atlético Madrid","atletico-madrid-colors"),
 "barcelona":("FC Barcelona","barcelona-fc-colors"),
 "celta_vigo":("Celta Vigo","rc-celta-de-vigo-color-codes"),
 "deportivo":("Deportivo La Coruña","deportivo-de-la-coruna-color-codes"),
 "elche":("Elche CF",None),
 "espanyol":("RCD Espanyol","rcd-espanyol-colors"),
 "getafe":("Getafe CF","getafe-cf-colors"),
 "levante":("Levante UD","levante-union-deportiva-color-codes"),
 "malaga":("Málaga CF",None),
 "osasuna":("CA Osasuna","osasuna-colors"),
 "racing_santander":("Racing Santander",None),
 "rayo_vallecano":("Rayo Vallecano",None),
 "real_betis":("Real Betis","real-betis-color-codes"),
 "real_madrid":("Real Madrid","real-madrid-c-f-colors"),
 "real_sociedad":("Real Sociedad","real-sociedad-colors"),
 "sevilla":("Sevilla FC","sevilla-fc-colors"),
 "valencia":("Valencia CF","valencia-c-f-color-codes"),
 "villarreal":("Villarreal CF","villarreal-cf-colors"),
}
SERIEA = {
 "atalanta":("Atalanta","atalanta-color-codes"),
 "bologna":("Bologna","bologna-fc-color-codes"),
 "cagliari":("Cagliari","cagliari-color-codes"),
 "como":("Como 1907",None),
 "fiorentina":("Fiorentina","fiorentina-color-codes"),
 "frosinone":("Frosinone",None),
 "genoa":("Genoa","genoa-colors"),
 "inter":("Inter Milan","inter-milan-color-codes"),
 "juventus":("Juventus","juventus-color-codes"),
 "lazio":("Lazio","lazio-colors"),
 "lecce":("Lecce","lecce-colors"),
 "milan":("AC Milan","a-c-milan-color-codes"),
 "monza":("Monza",None),
 "napoli":("Napoli","napoli-color-codes"),
 "parma":("Parma","parma-colors"),
 "roma":("AS Roma","a-s-roma-color-codes"),
 "sassuolo":("Sassuolo","sassuolo-colors"),
 "torino":("Torino","torino-colors"),
 "udinese":("Udinese","udinese-colors"),
 "venezia":("Venezia",None),
}
BUNDESLIGA = {
 "augsburg":("FC Augsburg","fc-augsburg-color-codes"),
 "union_berlin":("1. FC Union Berlin","1-fc-union-berlin-color-codes"),
 "werder_bremen":("Werder Bremen",None),
 "dortmund":("Borussia Dortmund","borussia-dortmund-color-codes"),
 "elversberg":("SV Elversberg",None),
 "eintracht_frankfurt":("Eintracht Frankfurt","eintracht-frankfurt-color-codes"),
 "freiburg":("SC Freiburg","sc-freiburg-color-codes"),
 "hamburg":("Hamburger SV",None),
 "hoffenheim":("TSG 1899 Hoffenheim","tsg-1899-hoffenheim-color-codes"),
 "koln":("1. FC Köln","1-fc-koln-color-codes"),
 "leipzig":("RB Leipzig","leipzig-colors"),
 "leverkusen":("Bayer 04 Leverkusen","bayer-04-leverkusen-color-codes"),
 "mainz":("1. FSV Mainz 05","1-fsv-mainz-05-color-codes"),
 "monchengladbach":("Borussia Mönchengladbach","borussia-monchengladbach-color-codes"),
 "bayern_munich":("Bayern Munich","bayern-munich-fc-colors"),
 "paderborn":("SC Paderborn 07",None),
 "schalke":("Schalke 04",None),
 "stuttgart":("VfB Stuttgart","vfb-stuttgart-color-codes"),
}
LIGUE1 = {
 "angers":("Angers SCO","angers-sco-color-codes"),
 "auxerre":("AJ Auxerre",None),
 "brest":("Stade Brestois 29","stade-brestois-29-color-codes"),
 "le_havre":("Le Havre AC",None),
 "le_mans":("Le Mans FC",None),
 "lens":("RC Lens","rc-lens-color-codes"),
 "lille":("Lille OSC","lille-osc-color-codes"),
 "lorient":("FC Lorient","fc-lorient-color-codes"),
 "lyon":("Olympique Lyonnais","lyon-colors"),
 "marseille":("Olympique de Marseille","olympique-de-marseille-color-codes"),
 "monaco":("AS Monaco","as-monaco-color-codes"),
 "nice":("OGC Nice","ogc-nice-color-codes"),
 "paris_fc":("Paris FC",None),
 "psg":("Paris Saint-Germain","paris-saint-germain-colors"),
 "rennes":("Stade Rennais","stade-rennais-color-codes"),
 "strasbourg":("RC Strasbourg Alsace","rc-strasbourg-alsace-color-codes"),
 "toulouse":("Toulouse FC",None),
 "troyes":("ES Troyes AC","es-troyes-ac-color-codes"),
}
MLS = {
 "atlanta_united":("Atlanta United FC","atlanta-united-fc-color-codes"),
 "austin":("Austin FC","austin-f-c-color-codes"),
 "cf_montreal":("CF Montréal","montreal-impact-color-codes"),
 "charlotte":("Charlotte FC","charlotte-fc-color-codes"),
 "chicago_fire":("Chicago Fire FC","chicago-fire-color-codes"),
 "colorado_rapids":("Colorado Rapids","colorado-rapids-team-color-codes"),
 "columbus_crew":("Columbus Crew","columbus-crew-sc-color-codes"),
 "dc_united":("D.C. United","d-c-united-team-color-codes"),
 "fc_cincinnati":("FC Cincinnati","cincinnati-fc-color-codes"),
 "fc_dallas":("FC Dallas","fc-dallas-color-codes"),
 "houston_dynamo":("Houston Dynamo FC","houston-dynamo-color-codes"),
 "inter_miami":("Inter Miami CF","inter-miami-cf-color-codes"),
 "la_galaxy":("LA Galaxy","la-galaxy-color-codes"),
 "lafc":("Los Angeles FC","los-angeles-fc-color-codes"),
 "minnesota_united":("Minnesota United FC","minnesota-united-fc-colors"),
 "nashville":("Nashville SC","nashville-sc-color-codes"),
 "new_england":("New England Revolution","new-england-revolution-color-codes"),
 "nycfc":("New York City FC","new-york-city-fc-color-codes"),
 "ny_red_bulls":("New York Red Bulls","new-york-red-bulls-color-codes"),
 "orlando_city":("Orlando City SC","orlando-city-sc-color-codes"),
 "philadelphia_union":("Philadelphia Union","philadelphia-union-color-codes"),
 "portland_timbers":("Portland Timbers","portland-timbers-color-codes"),
 "real_salt_lake":("Real Salt Lake","real-salt-lake-color-codes"),
 "san_diego":("San Diego FC",None),
 "san_jose":("San Jose Earthquakes","san-jose-earthquakes-color-codes"),
 "seattle_sounders":("Seattle Sounders FC","seattle-sounders-fc-color-codes"),
 "sporting_kc":("Sporting Kansas City","sporting-kansas-city-color-codes"),
 "st_louis_city":("St. Louis City SC",None),
 "toronto_fc":("Toronto FC","toronto-fc-color-codes"),
 "vancouver":("Vancouver Whitecaps FC","vancouver-whitecaps-fc-color-codes"),
}

RETAINED_EPL = {
  "burnley":("Burnley","burnley-football-club-colors"),
  "leicester":("Leicester City","leicester-city-football-club-colors"),
  "middlesbrough":("Middlesbrough","middlesbrough-f-c-color-codes"),
  "southampton":("Southampton","southampton-fc-colors"),
  "stoke_city":("Stoke City","stoke-city-fc"),
  "swansea_city":("Swansea City","swansea-city-afc-colors"),
  "watford":("Watford","watford-fc-colors"),
  "west_bromich_albion":("West Bromwich Albion","west-bromwich-albion-colors"),
  "west_ham":("West Ham United","west-ham-united-colors"),
}
EPL.update(RETAINED_EPL)

LEAGUES = {"epl":EPL,"laliga":LALIGA,"seriea":SERIEA,"bundesliga":BUNDESLIGA,"ligue1":LIGUE1,"mls":MLS}
