MLB = {
 "diamondbacks":("Arizona Diamondbacks","arizona-diamondbacks-color-codes"),
 "braves":("Atlanta Braves","atlanta-braves-color-codes"),
 "orioles":("Baltimore Orioles","baltimore-orioles-color-codes"),
 "red_sox":("Boston Red Sox","boston-red-sox-color-codes"),
 "cubs":("Chicago Cubs","chicago-cubs-color-codes"),
 "white_sox":("Chicago White Sox","chicago-white-sox-color-codes"),
 "reds":("Cincinnati Reds","cincinnati-reds-color-codes"),
 "guardians":("Cleveland Guardians","cleveland-indians-color-codes"),
 "rockies":("Colorado Rockies","colorado-rockies-color-codes"),
 "tigers":("Detroit Tigers","detroit-tigers-color-codes"),
 "astros":("Houston Astros","houston-astros-color-codes"),
 "royals":("Kansas City Royals","kansas-city-royals-color-codes"),
 "angels":("Los Angeles Angels","los-angeles-angels-color-codes"),
 "dodgers":("Los Angeles Dodgers","los-angeles-dodgers-color-codes"),
 "marlins":("Miami Marlins","miami-marlins-color-codes"),
 "brewers":("Milwaukee Brewers","milwaukee-brewers-color-codes"),
 "twins":("Minnesota Twins","minnesota-twins-color-codes"),
 "mets":("New York Mets","new-york-mets-color-codes"),
 "yankees":("New York Yankees","new-york-yankees-color-codes"),
 "athletics":("Athletics","oakland-athletics-color-codes"),
 "phillies":("Philadelphia Phillies","philadelphia-phillies-color-codes"),
 "pirates":("Pittsburgh Pirates","pittsburgh-pirates-color-codes"),
 "padres":("San Diego Padres","san-diego-padres-color-codes"),
 "giants":("San Francisco Giants","san-francisco-giants-color-codes"),
 "mariners":("Seattle Mariners","seattle-mariners-color-codes"),
 "cardinals":("St. Louis Cardinals","st-louis-cardinals-color-codes"),
 "rays":("Tampa Bay Rays","tampa-bay-rays-color-codes"),
 "rangers":("Texas Rangers","texas-rangers-color-codes"),
 "blue_jays":("Toronto Blue Jays","toronto-blue-jays-color-codes"),
 "nationals":("Washington Nationals","washington-nationals-color-codes"),
}
NBA = {
 "hawks":("Atlanta Hawks","atlanta-hawks-color-codes"),
 "celtics":("Boston Celtics","boston-celtics-color-codes"),
 "nets":("Brooklyn Nets","brooklyn-nets-color-codes"),
 "hornets":("Charlotte Hornets","charlotte-hornets-color-codes"),
 "bulls":("Chicago Bulls","chicago-bulls-color-codes"),
 "cavs":("Cleveland Cavaliers","cleveland-cavaliers-color-codes"),
 "mavs":("Dallas Mavericks","dallas-mavericks-color-codes"),
 "nuggets":("Denver Nuggets","denver-nuggets-color-codes"),
 "pistons":("Detroit Pistons","detroit-pistons-color-codes"),
 "warriors":("Golden State Warriors","golden-state-warriors-color-codes"),
 "rockets":("Houston Rockets","houston-rockets-color-codes"),
 "pacers":("Indiana Pacers","indiana-pacers-color-codes"),
 "clippers":("Los Angeles Clippers","los-angeles-clippers-color-codes"),
 "lakers":("Los Angeles Lakers","los-angeles-lakers-color-codes"),
 "grizzlies":("Memphis Grizzlies","memphis-grizzlies-color-codes"),
 "heat":("Miami Heat","miami-heat-color-codes"),
 "bucks":("Milwaukee Bucks","milwaukee-bucks-color-codes"),
 "wolves":("Minnesota Timberwolves","minnesota-timberwolves-color-codes"),
 "pelicans":("New Orleans Pelicans","new-orleans-pelicans-team-color-codes"),
 "knicks":("New York Knicks","new-york-knicks-color-codes"),
 "thunder":("Oklahoma City Thunder","oklahoma-city-thunder-color-codes"),
 "magic":("Orlando Magic","orlando-magic-color-codes"),
 "sixers":("Philadelphia 76ers","philadelphia-76ers-color-codes"),
 "suns":("Phoenix Suns","phoenix-suns-color-codes"),
 "blazers":("Portland Trail Blazers","portland-trailblazers-color-codes"),
 "kings":("Sacramento Kings","sacramento-kings-color-codes"),
 "spurs":("San Antonio Spurs","san-antonio-spurs-color-codes"),
 "raptors":("Toronto Raptors","toronto-raptors-color-codes"),
 "jazz":("Utah Jazz","utah-jazz-color-codes"),
 "wizards":("Washington Wizards","washington-wizards-color-codes"),
 "sonics":("Seattle SuperSonics","seattle-supersonics-colors"),
}
NFL = {
 "cardinals":("Arizona Cardinals","arizona-cardinals-color-codes"),
 "falcons":("Atlanta Falcons","atlanta-falcons-color-codes"),
 "ravens":("Baltimore Ravens","baltimore-ravens-color-codes"),
 "bills":("Buffalo Bills","buffalo-bills-color-codes"),
 "panthers":("Carolina Panthers","carolina-panthers-color-codes"),
 "bears":("Chicago Bears","chicago-bears-color-codes"),
 "bengals":("Cincinnati Bengals","cincinnati-bengals-color-codes"),
 "browns":("Cleveland Browns","cleveland-browns-color-codes"),
 "cowboys":("Dallas Cowboys","dallas-cowboys-color-codes"),
 "broncos":("Denver Broncos","denver-broncos-color-codes"),
 "lions":("Detroit Lions","detroit-lions-color-codes"),
 "packers":("Green Bay Packers","green-bay-packers-color-codes"),
 "texans":("Houston Texans","houston-texans-color-codes"),
 "colts":("Indianapolis Colts","indianapolis-colts-color-codes"),
 "jaguars":("Jacksonville Jaguars","jacksonville-jaguars-color-codes"),
 "chiefs":("Kansas City Chiefs","kansas-city-chiefs-color-codes"),
 "raiders":("Las Vegas Raiders","oakland-raiders-color-codes"),
 "chargers":("Los Angeles Chargers","los-angeles-chargers-color-codes"),
 "rams":("Los Angeles Rams","los-angeles-rams-team-colors"),
 "dolphins":("Miami Dolphins","miami-dolphins-color-codes"),
 "vikings":("Minnesota Vikings","minnesota-vikings-color-codes"),
 "patriots":("New England Patriots","new-england-patriots-color-codes"),
 "saints":("New Orleans Saints","new-orleans-saints-color-codes"),
 "giants":("New York Giants","new-york-giants-color-codes"),
 "jets":("New York Jets","new-york-jets-color-codes"),
 "eagles":("Philadelphia Eagles","philadelphia-eagles-color-codes"),
 "steelers":("Pittsburgh Steelers","pittsburgh-steelers-color-codes"),
 "niners":("San Francisco 49ers","san-francisco-49ers-team-colors"),
 "seahawks":("Seattle Seahawks","seattle-seahawks-color-codes"),
 "buccaneers":("Tampa Bay Buccaneers","tampa-bay-buccaneers-team-colors"),
 "titans":("Tennessee Titans","tennessee-titans-color-codes"),
 "commanders":("Washington Commanders","washington-redskins-color-codes"),
}
NHL = {
 "ducks":("Anaheim Ducks","anaheim-ducks-color-codes"),
 "bruins":("Boston Bruins","boston-bruins-color-codes"),
 "sabres":("Buffalo Sabres","buffalo-sabres-color-codes"),
 "flames":("Calgary Flames","calgary-flames-color-codes"),
 "hurricanes":("Carolina Hurricanes","carolina-hurricanes-color-codes"),
 "blackhawks":("Chicago Blackhawks","chicago-blackhawks-color-codes"),
 "avalanche":("Colorado Avalanche","colorado-avalanche-color-codes"),
 "blue_jackets":("Columbus Blue Jackets","columbus-blue-jackets-color-codes"),
 "stars":("Dallas Stars","dallas-stars-color-codes"),
 "red_wings":("Detroit Red Wings","detroit-red-wings-color-codes"),
 "oilers":("Edmonton Oilers","edmonton-oilers-color-codes"),
 "panthers":("Florida Panthers","florida-panthers-color-codes"),
 "kings":("Los Angeles Kings","los-angeles-kings-color-codes"),
 "wild":("Minnesota Wild","minnesota-wild-color-codes"),
 "canadiens":("Montreal Canadiens","montreal-canadiens-color-codes"),
 "predators":("Nashville Predators","nashville-predators-color-codes"),
 "devils":("New Jersey Devils","new-jersey-devils-color-codes"),
 "islanders":("New York Islanders","new-york-islanders-color-codes"),
 "rangers":("New York Rangers","new-york-rangers-color-codes"),
 "senators":("Ottawa Senators","ottawa-senators-color-codes"),
 "flyers":("Philadelphia Flyers","philadelphia-flyers-color-codes"),
 "penguins":("Pittsburgh Penguins","pittsburgh-penguins-color-codes"),
 "sharks":("San Jose Sharks","san-jose-sharks-color-codes"),
 "kraken":("Seattle Kraken","seattle-kraken-colors"),
 "blues":("St. Louis Blues","st-louis-blues-color-codes"),
 "lightning":("Tampa Bay Lightning","tampa-bay-lightning-color-codes"),
 "maple_leafs":("Toronto Maple Leafs","toronto-maple-leafs-color-codes"),
 "utah":("Utah Mammoth",None),
 "canucks":("Vancouver Canucks","vancouver-canucks-color-codes"),
 "golden_knights":("Vegas Golden Knights","vegas-golden-knights-colors"),
 "capitals":("Washington Capitals","washington-capitals-color-codes"),
 "jets":("Winnipeg Jets","winnipeg-jets-color-codes"),
 "coyotes":("Arizona Coyotes","arizona-coyotes-color-codes"),
}
US = {"mlb":MLB,"nba":NBA,"nfl":NFL,"nhl":NHL}

WNBA = {
 "dream":("Atlanta Dream","atlanta-dreams-color-codes"),
 "sky":("Chicago Sky","chicago-sky-color-codes"),
 "sun":("Connecticut Sun","connecticut-sun-color-codes"),
 "wings":("Dallas Wings","dallas-wings-color-codes"),
 "valkyries":("Golden State Valkyries",None),
 "fever":("Indiana Fever","indiana-fever-color-codes"),
 "aces":("Las Vegas Aces","las-vegas-aces-color-codes"),
 "sparks":("Los Angeles Sparks","los-angeles-sparks-color-codes"),
 "lynx":("Minnesota Lynx","minnesota-lynx-color-codes"),
 "liberty":("New York Liberty","new-york-liberty-color-codes"),
 "mercury":("Phoenix Mercury","phoenix-mercury-color-codes"),
 "fire":("Portland Fire",None),
 "storm":("Seattle Storm","seattle-storm-color-codes"),
 "tempo":("Toronto Tempo",None),
 "mystics":("Washington Mystics","washington-mystics-color-codes"),
}
US["wnba"] = WNBA
