# Generated by data-raw/build_palettes.py -- do not edit by hand.

#' @noRd
.colorr_leagues_meta <- list(
  epl = list(label = "English Premier League", soccer = TRUE),
  laliga = list(label = "LaLiga", soccer = TRUE),
  seriea = list(label = "Serie A", soccer = TRUE),
  bundesliga = list(label = "Bundesliga", soccer = TRUE),
  ligue1 = list(label = "Ligue 1", soccer = TRUE),
  mls = list(label = "Major League Soccer", soccer = TRUE),
  mlb = list(label = "Major League Baseball", soccer = FALSE),
  nba = list(label = "National Basketball Association", soccer = FALSE),
  wnba = list(label = "Women's National Basketball Association", soccer = FALSE),
  nfl = list(label = "National Football League", soccer = FALSE),
  nhl = list(label = "National Hockey League", soccer = FALSE)
)
