# Generated by data-raw/build_palettes.py -- do not edit by hand.
# Sources are listed in data-raw/provenance.json and in the package README.

#' @noRd
.colorr_palettes <- list(
  epl = list(
    arsenal = c("Red" = "#EF0107",
                "Dark Red" = "#DB0007",
                "Blue" = "#063672",
                "Gold" = "#9C824A",
                "White" = "#FFFFFF"),  # Arsenal
    aston_villa = c("Blue" = "#95BFE5",
                    "Claret" = "#670E36",
                    "Yellow" = "#FEE505"),  # Aston Villa
    bournemouth = c("Red" = "#DA291C",
                    "Dark Red" = "#B50E12",
                    "Black" = "#000000",
                    "Light Gold" = "#EFDBB2",
                    "Dark Gold" = "#A89968"),  # AFC Bournemouth
    brentford = c("Red" = "#D20000",
                  "White" = "#FFFFFF",
                  "Off White" = "#E9E5DA",
                  "Orange" = "#FFB400",
                  "Black" = "#000000"),  # Brentford
    brighton = c("Blue" = "#0A56A3",
                 "Yellow" = "#FFCD00"),  # Brighton & Hove Albion
    burnley = c("Burgundy" = "#6C1D45",
                "Light Blue" = "#99D6EA",
                "Yellow" = "#EDE939",
                "Gold" = "#F0B323"),  # Burnley
    chelsea = c("Blue" = "#034694",
                "Red" = "#EE242C",
                "Gold" = "#DBA111",
                "Light Blue" = "#6A7AB5",
                "Gray" = "#D1D3D4"),  # Chelsea
    coventry_city = c("Sky Blue" = "#059DD9",
                      "White" = "#FFFFFF"),  # Coventry City
    crystal_palace = c("Blue" = "#1B458F",
                       "Gray" = "#A7A5A6",
                       "Red" = "#C4122E"),  # Crystal Palace
    everton = c("Blue" = "#003399",
                "White" = "#FFFFFF"),  # Everton
    fulham = c("Black" = "#000000",
               "Red" = "#CC0000",
               "White" = "#FFFFFF"),  # Fulham
    hull = c("Black" = "#000000",
             "Blue" = "#F18A01",
             "White" = "#FFFFFF"),  # Hull City
    ipswich_town = c("Blue" = "#3A64A3",
                     "Red" = "#DE2C37",
                     "White" = "#FEFEFE"),  # Ipswich Town
    leeds_united = c("Yellow" = "#FFCD00",
                     "Blue" = "#1D428A",
                     "100th Anniversary Gold" = "#AC944D"),  # Leeds United
    leicester = c("Blue" = "#003090",
                  "Gold" = "#FDBE11"),  # Leicester City
    liverpool = c("Red" = "#C8102E",
                  "Green" = "#00B2A9",
                  "Gold" = "#F6EB61"),  # Liverpool
    man_city = c("Sky Blue" = "#6CABDD",
                 "Blue" = "#1C2C5B",
                 "Gold" = "#FFC659",
                 "Dark Gold" = "#D4A12A",
                 "Red" = "#EC3325"),  # Manchester City
    man_united = c("Red" = "#DA291C",
                   "Yellow" = "#FBE122"),  # Manchester United
    middlesbrough = c("Red" = "#DE1B22",
                      "White" = "#FFFFFF"),  # Middlesbrough
    newcastle = c("Black" = "#241F20",
                  "White" = "#FFFFFF",
                  "Blue" = "#41B6E6",
                  "Gold" = "#F1BE48",
                  "Gray" = "#BBBCBC",
                  "Red" = "#F9423A"),  # Newcastle United
    nottingham_forest = c("Red" = "#DD0000",
                          "White" = "#FFFFFF"),  # Nottingham Forest
    southampton = c("Red" = "#D71920",
                    "Black" = "#130C0E",
                    "Yellow" = "#FFC20E",
                    "Blue" = "#00AEEF",
                    "Green" = "#0DB14B"),  # Southampton
    stoke_city = c("Red" = "#E03A3E",
                   "Blue" = "#1B449C"),  # Stoke City
    sunderland = c("Red" = "#EB172B",
                   "White" = "#FFFFFF",
                   "Gold" = "#A68A26",
                   "Pale Gold" = "#D1BF7F",
                   "Black" = "#211E1E"),  # Sunderland
    swansea_city = c("Black" = "#000000",
                     "White" = "#FFFFFF"),  # Swansea City
    tottenham = c("Navy Blue" = "#132257"),  # Tottenham Hotspur
    watford = c("Yellow" = "#FBEE23",
                "Red" = "#ED2127",
                "Black" = "#11210C"),  # Watford
    west_bromich_albion = c("Blue" = "#122F67",
                            "White" = "#FFFFFF"),  # West Bromwich Albion
    west_ham = c("Maroon" = "#7A263A",
                 "Blue" = "#1BB1E7",
                 "Yellow" = "#F3D459")  # West Ham United
  ),

  laliga = list(
    alaves = c("Royal Blue" = "#0761AF",
               "Light Blue" = "#009AD7"),  # Deportivo Alaves
    athletic_bilbao = c("White" = "#FFFFFF",
                        "Red" = "#EE2523",
                        "Black" = "#000000"),  # Athletic Bilbao
    atletico_madrid = c("Navy Blue" = "#272E61",
                        "White" = "#FFFFFF",
                        "Red" = "#CB3524"),  # Atletico Madrid
    barcelona = c("Gold" = "#EDBB00",
                  "Blue" = "#004D98",
                  "Burgundy" = "#A50044",
                  "Red" = "#DB0030",
                  "Yellow" = "#FFED02",
                  "Buy Matching Paint" = "#FFDD00",
                  "Black" = "#000000"),  # FC Barcelona
    celta_vigo = c("Blue" = "#8AC3EE",
                   "Red" = "#E5254E",
                   "Gold" = "#B19221"),  # Celta Vigo
    deportivo = c("Purple" = "#57175E",
                  "Gold" = "#A38D44",
                  "Blue" = "#B9D9EC",
                  "Red" = "#DB5232"),  # Deportivo La Coruna
    elche = c("Dark Gold" = "#866B10",
              "Gold" = "#E6C777",
              "White" = "#FFFFFF",
              "Red" = "#C5112E",
              "Blue" = "#1B458F",
              "Green" = "#05642C"),  # Elche CF
    espanyol = c("White" = "#FFFFFF",
                 "Blue" = "#007FC8",
                 "Red" = "#DF1116",
                 "Yellow" = "#F4CF0C"),  # RCD Espanyol
    getafe = c("Blue" = "#005999",
               "Red" = "#C43A2F",
               "Yellow" = "#FCED0B",
               "White" = "#FFFFFF",
               "Green" = "#7DA738"),  # Getafe CF
    levante = c("Maroon" = "#B4053F",
                "Blue" = "#005CA5",
                "Gold" = "#DCA43E",
                "Yellow" = "#FAC400",
                "Gray" = "#B2B2B2"),  # Levante UD
    malaga = c("Dark Red" = "#4C2A1F",
               "Orange" = "#C86606",
               "Gold" = "#C39400",
               "Gold" = "#FFF26B",
               "Black" = "#1D1D1B",
               "White" = "#FFFFFF",
               "Light Blue" = "#A7D6F5",
               "Blue" = "#00489A"),  # Malaga CF
    osasuna = c("Blue" = "#0A346F",
                "Red" = "#D91A21",
                "White" = "#FFFFFF",
                "Gold" = "#AD8F1F"),  # CA Osasuna
    racing_santander = c("Green" = "#45AC34",
                         "Dark Green" = "#1C5733",
                         "White" = "#FFFFFF"),  # Racing Santander
    rayo_vallecano = c("Red" = "#E3361D",
                       "Gold" = "#C0AE33",
                       "Black" = "#251900",
                       "White" = "#FFFFFF",
                       "Forest Green" = "#008A3A"),  # Rayo Vallecano
    real_betis = c("Green" = "#0BB363",
                   "Gold" = "#E7A614",
                   "Red" = "#D62550"),  # Real Betis
    real_madrid = c("Gold" = "#FEBE10",
                    "Blue" = "#00529F",
                    "Red" = "#EE324E"),  # Real Madrid
    real_sociedad = c("White" = "#FFFFFF",
                      "Blue" = "#0067B1",
                      "Yellow" = "#E4B630",
                      "Gold" = "#D87722",
                      "Red" = "#E1061F"),  # Real Sociedad
    sevilla = c("White" = "#FFFFFF",
                "Red" = "#F43333",
                "Gold" = "#C79100"),  # Sevilla FC
    valencia = c("Blue" = "#0097D7",
                 "Yellow" = "#FFDF1C",
                 "Red" = "#EE3524",
                 "Red-Orange" = "#AA2D2A",
                 "Yellow-Orange" = "#D18816",
                 "Black" = "#000000"),  # Valencia CF
    villarreal = c("Blue" = "#005187",
                   "Yellow" = "#FFE667",
                   "Red" = "#E70005",
                   "Black" = "#000000")  # Villarreal CF
  ),

  seriea = list(
    atalanta = c("Blue" = "#1E71B8",
                 "Black" = "#000000"),  # Atalanta
    bologna = c("Navy Blue" = "#1A2F48",
                "Red" = "#A21C26",
                "White" = "#FFFFFF",
                "Light Silver" = "#ECECEC"),  # Bologna
    cagliari = c("Navy Blue" = "#002350",
                 "Red" = "#AD002A",
                 "White" = "#FFFFFF"),  # Cagliari
    como = c("Navy Blue" = "#10416A",
             "White" = "#FFFFFF"),  # Como 1907
    fiorentina = c("Violet (Purple)" = "#482E92",
                   "Gold" = "#A29160",
                   "Red" = "#EC1C23",
                   "White" = "#FFFFFF"),  # Fiorentina
    frosinone = c("Yellow" = "#FFDD00",
                  "Dark Blue" = "#004393",
                  "Blue" = "#006AB3",
                  "Light Blue" = "#C8D6EC",
                  "Black" = "#000000",
                  "Grey" = "#868889"),  # Frosinone
    genoa = c("Red" = "#AD1919",
              "Dark Blue" = "#05232F",
              "Yellow" = "#FFD400",
              "White" = "#FFFFFF"),  # Genoa
    inter = c("Black" = "#000000",
              "Blue" = "#010E80"),  # Inter Milan
    juventus = c("Black" = "#000000",
                 "White" = "#FFFFFF"),  # Juventus
    lazio = c("Sky Blue" = "#87D8F7",
              "White" = "#FFFFFF",
              "Dark Blue" = "#15366F",
              "Gold" = "#D7A819"),  # Lazio
    lecce = c("Red" = "#ED1B23",
              "Yellow" = "#FFF200",
              "Blue" = "#006086",
              "Light Brown" = "#D1B48F"),  # Lecce
    milan = c("Red" = "#FB090B",
              "Black" = "#000000"),  # AC Milan
    monza = c("Red" = "#E4022E",
              "White" = "#FFFFFF"),  # Monza
    napoli = c("Blue" = "#003C82",
               "Light Blue" = "#12A0D7",
               "White" = "#FFFFFF"),  # Napoli
    parma = c("Blue" = "#1B4094",
              "Yellow" = "#FFD200",
              "White" = "#FFFFFF"),  # Parma
    roma = c("Giallo Roma" = "#F0BC42",
             "Rosso Roma" = "#8E1F2F",
             "Gray" = "#CACACC",
             "Black" = "#000000"),  # AS Roma
    sassuolo = c("Green" = "#00A752",
                 "Black" = "#000000",
                 "White" = "#FFFFFF",
                 "Grey" = "#C7C7C7"),  # Sassuolo
    torino = c("Red" = "#8A1E03",
               "Yellow" = "#EEB111",
               "Blue" = "#5E91CC",
               "White" = "#FFFFFF"),  # Torino
    udinese = c("Black" = "#000000",
                "White" = "#FFFFFF",
                "Gold" = "#8B7D37",
                "Grey" = "#7F7F7F"),  # Udinese
    venezia = c("Green" = "#436817",
                "Orange" = "#EF7D00",
                "White" = "#FFFFFF",
                "Black" = "#000000",
                "Red" = "#AD1917",
                "Grey" = "#696D72")  # Venezia
  ),

  bundesliga = list(
    augsburg = c("Red" = "#BA3733",
                 "Green" = "#46714D",
                 "White" = "#FFFFFF",
                 "Black" = "#000000",
                 "Yellow" = "#FFD42E"),  # FC Augsburg
    bayern_munich = c("Blue" = "#0066B2",
                      "Red" = "#DC052D"),  # Bayern Munich
    dortmund = c("Yellow" = "#FDE100",
                 "Black" = "#000000"),  # Borussia Dortmund
    eintracht_frankfurt = c("Red" = "#E1000F",
                            "White" = "#FFFFFF",
                            "Black" = "#000000"),  # Eintracht Frankfurt
    elversberg = c("Gold" = "#C8B885",
                   "Black" = "#141414",
                   "White" = "#FFFFFF"),  # SV Elversberg
    freiburg = c("Black" = "#000000",
                 "White" = "#FFFFFF",
                 "Red" = "#FD1220"),  # SC Freiburg
    hamburg = c("Blue" = "#1E5CB3",
                "White" = "#FFFFFF",
                "Black" = "#000000"),  # Hamburger SV
    hoffenheim = c("Blue" = "#1961B5",
                   "White" = "#FFFFFF"),  # TSG 1899 Hoffenheim
    koln = c("Red" = "#ED1C24",
             "White" = "#FFFFFF",
             "Black" = "#000000"),  # 1. FC Koln
    leipzig = c("Red" = "#DD013F",
                "Dark Blue" = "#0C2043",
                "White" = "#FFFFFF"),  # RB Leipzig
    leverkusen = c("Red" = "#E32221",
                   "Black" = "#000000",
                   "White" = "#FFFFFF",
                   "Yellow" = "#F3E500"),  # Bayer 04 Leverkusen
    mainz = c("Red" = "#C3141E",
              "White" = "#FFFFFF",
              "Gray" = "#918F90"),  # 1. FSV Mainz 05
    monchengladbach = c("Black" = "#000000",
                        "White" = "#FFFFFF"),  # Borussia Monchengladbach
    paderborn = c("Black" = "#000000",
                  "White" = "#FFFFFF",
                  "Blue" = "#005CA8"),  # SC Paderborn 07
    schalke = c("Blue" = "#004B9C",
                "White" = "#FFFFFF"),  # Schalke 04
    stuttgart = c("Red" = "#E32219",
                  "White" = "#FFFFFF",
                  "Yellow" = "#FFED00",
                  "Black" = "#000000"),  # VfB Stuttgart
    union_berlin = c("Red" = "#EB1923",
                     "Yellow" = "#FDDC02",
                     "White" = "#FFFFFF",
                     "Black" = "#000000"),  # 1. FC Union Berlin
    werder_bremen = c("Green" = "#009655",
                      "White" = "#FFFFFF")  # Werder Bremen
  ),

  ligue1 = list(
    angers = c("Black" = "#000000",
               "White" = "#FFFFFF",
               "Gold" = "#D9C395"),  # Angers SCO
    auxerre = c("Blue" = "#1C4F9C",
                "White" = "#FFFFFF"),  # AJ Auxerre
    brest = c("Red" = "#ED1C24",
              "White" = "#FFFFFF",
              "Black" = "#000000"),  # Stade Brestois 29
    le_havre = c("Blue" = "#003259",
                 "Black" = "#000000",
                 "Gold" = "#B9955D",
                 "White" = "#FFFFFF",
                 "Light Blue" = "#8BC4E5"),  # Le Havre AC
    le_mans = c("Red" = "#D60000",
                "Yellow" = "#FECB00",
                "Dark Grey" = "#343434"),  # Le Mans FC
    lens = c("Red" = "#EC1C24",
             "Yellow" = "#FFF200",
             "White" = "#FFFFFF",
             "Black" = "#000000"),  # RC Lens
    lille = c("Red" = "#E01E13",
              "Blue" = "#24216A",
              "White" = "#FFFFFF"),  # Lille OSC
    lorient = c("Orange" = "#F58113",
                "Black" = "#000000",
                "White" = "#FFFFFF"),  # FC Lorient
    lyon = c("Red" = "#DA0812",
             "Blue" = "#14387F",
             "White" = "#FFFFFF",
             "Gold" = "#D29D46"),  # Olympique Lyonnais
    marseille = c("Blue" = "#2FAEE0",
                  "Gold" = "#BEA064",
                  "White" = "#FFFFFF"),  # Olympique de Marseille
    monaco = c("Red" = "#E51B22",
               "Gold" = "#CB9F18",
               "White" = "#FFFFFF"),  # AS Monaco
    nice = c("Black" = "#000000",
             "Red" = "#ED1C24",
             "Gold" = "#B59A54",
             "White" = "#FFFFFF"),  # OGC Nice
    paris_fc = c("Dark Blue" = "#0C183F",
                 "Blue" = "#0680BE",
                 "White" = "#FFFFFF",
                 "Red" = "#BD3032"),  # Paris FC
    psg = c("Blue" = "#004170",
            "White" = "#FFFFFF",
            "Red" = "#DA291C",
            "Gold" = "#CEAB5D"),  # Paris Saint-Germain
    rennes = c("Red" = "#E13327",
               "Black" = "#000000",
               "Gold" = "#FCBC17",
               "White" = "#FFFFFF"),  # Stade Rennais
    strasbourg = c("Blue" = "#009FE3",
                   "Red" = "#DC2F34",
                   "Navy Blue" = "#004996",
                   "White" = "#FFFFFF",
                   "Black" = "#000000"),  # RC Strasbourg Alsace
    toulouse = c("Purple" = "#3F2A56",
                 "Light Purple" = "#745990",
                 "White" = "#FFFFFF",
                 "Red" = "#EA0046",
                 "Gold" = "#E2B77F"),  # Toulouse FC
    troyes = c("Blue" = "#006EB2",
               "Gold" = "#DC9D0F",
               "White" = "#FFFFFF")  # ES Troyes AC
  ),

  mls = list(
    atlanta_united = c("Dark Red" = "#80000A",
                       "Black" = "#221F1F",
                       "Metallic Gold" = "#A19060",
                       "Dark Gold" = "#817144"),  # Atlanta United FC
    austin = c("Bright Verde" = "#00B140",
               "Black" = "#000000",
               "White" = "#FFFFFF"),  # Austin FC
    cf_montreal = c("Black" = "#000000",
                    "Ice Gray" = "#9EA1A2",
                    "Sacre Bleu" = "#0033A1"),  # CF Montreal
    charlotte = c("Black" = "#000000",
                  "Process Blue" = "#1A85C8"),  # Charlotte FC
    chicago_fire = c("Fire Red" = "#FF0000",
                     "Deep Blue" = "#141946",
                     "Flag Blue" = "#7CCDEF",
                     "White" = "#FFFFFF"),  # Chicago Fire FC
    colorado_rapids = c("Burgundy" = "#960A2C",
                        "Sky Blue" = "#9CC2EA",
                        "Silver" = "#D3D5D7"),  # Colorado Rapids
    columbus_crew = c("Yellow" = "#FEDD00",
                      "Black" = "#000000"),  # Columbus Crew
    dc_united = c("Red" = "#EF3E42",
                  "Black" = "#231F20",
                  "White" = "#FFFFFF"),  # D.C. United
    fc_cincinnati = c("Orange" = "#F05323",
                      "Blue" = "#263B80"),  # FC Cincinnati
    fc_dallas = c("Republic Red" = "#E81F3E",
                  "Bovine Blue" = "#2A4076",
                  "Shawnee Silver" = "#CCCBCC"),  # FC Dallas
    houston_dynamo = c("Raven Black" = "#101820",
                       "Wildcatter Orange" = "#FF6B00"),  # Houston Dynamo FC
    inter_miami = c("Pink" = "#F7B5CD",
                    "Black" = "#231F20"),  # Inter Miami CF
    la_galaxy = c("Navy Blue" = "#00245D",
                  "Blue" = "#0065A4",
                  "Gold" = "#FFD200",
                  "White" = "#FFFFFF"),  # LA Galaxy
    lafc = c("Black" = "#000000",
             "California Gold" = "#C39E6D",
             "Glory Red" = "#E31837",
             "Asphalt" = "#55565A",
             "Gray" = "#B3B2B1"),  # Los Angeles FC
    minnesota_united = c("Gray" = "#E4E5E6",
                         "Sky Blue" = "#8CD2F4",
                         "Black" = "#231F20"),  # Minnesota United FC
    nashville = c("Electric Gold" = "#ECE83A",
                  "Acoustic Blue" = "#1F1646"),  # Nashville SC
    new_england = c("Red" = "#CE0E2D",
                    "Blue" = "#0A2240"),  # New England Revolution
    ny_red_bulls = c("Red" = "#ED1E36",
                     "Blue" = "#23326A",
                     "Yellow" = "#FABB23",
                     "White" = "#FFFFFF"),  # New York Red Bulls
    nycfc = c("Sky Blue" = "#6CACE4",
              "Obsidian Blue" = "#041E42",
              "Flag Orange" = "#F15524"),  # New York City FC
    orlando_city = c("Purple" = "#633492",
                     "Gold" = "#FDE192"),  # Orlando City SC
    philadelphia_union = c("Navy Blue" = "#071B2C",
                           "Gold" = "#B19B69",
                           "Signal Blue" = "#3E8EDE"),  # Philadelphia Union
    portland_timbers = c("Green" = "#00482B",
                         "Gold" = "#D69A00"),  # Portland Timbers
    real_salt_lake = c("Claret Red" = "#B30838",
                       "Cobalt Blue" = "#013A81",
                       "Real Gold" = "#F1CB00"),  # Real Salt Lake
    san_diego = c("Dark Blue" = "#02152B",
                  "Gray" = "#697A7C",
                  "White" = "#FFFFFF",
                  "Orange" = "#F89E1A",
                  "Red" = "#EC2623",
                  "Blue" = "#0054A5"),  # San Diego FC
    san_jose = c("Black" = "#000000",
                 "Blue" = "#0067B1",
                 "Red" = "#E31837",
                 "White" = "#FFFFFF"),  # San Jose Earthquakes
    seattle_sounders = c("Sounder Blue" = "#005595",
                         "Rave Green" = "#5D9741",
                         "Cascade Shale" = "#142530"),  # Seattle Sounders FC
    sporting_kc = c("Sporting Blue" = "#91B0D5",
                    "Dark Indigo" = "#002F65",
                    "Lead" = "#999999"),  # Sporting Kansas City
    st_louis_city = c("Blue" = "#001837",
                      "White" = "#FFFFFF",
                      "Red" = "#DD004A"),  # St. Louis City SC
    toronto_fc = c("Red" = "#B81137",
                   "Black" = "#000000",
                   "Dark Gray" = "#455560",
                   "Gray" = "#B0B7BB",
                   "White" = "#FFFFFF"),  # Toronto FC
    vancouver = c("Deep Sea Blue" = "#00245E",
                  "Whitecaps Blue" = "#9DC2EA",
                  "White" = "#FFFFFF")  # Vancouver Whitecaps FC
  ),

  mlb = list(
    angels = c("Midnight Blue" = "#003263",
               "Red" = "#BA0021",
               "Maroon" = "#862633",
               "Silver" = "#C4CED4",
               "White" = "#FFFFFF"),  # Los Angeles Angels
    astros = c("Navy" = "#002D62",
               "Orange" = "#EB6E1F",
               "Light Orange" = "#F4911E"),  # Houston Astros
    athletics = c("Green" = "#003831",
                  "Gold" = "#EFB21E",
                  "Gray" = "#A2AAAD",
                  "Green" = "#115740",
                  "Yellow" = "#FFCD00"),  # Athletics
    blue_jays = c("Blue" = "#134A8E",
                  "Navy Blue" = "#1D2D5C",
                  "Red" = "#E8291C"),  # Toronto Blue Jays
    braves = c("Scarlet" = "#CE1141",
               "Navy" = "#13274F",
               "Gold" = "#EAAA00",
               "White" = "#FFFFFF"),  # Atlanta Braves
    brewers = c("Yellow" = "#FFC52F",
                "Navy Blue" = "#12284B"),  # Milwaukee Brewers
    cardinals = c("Cardinal Red" = "#C41E3A",
                  "Navy" = "#0C2340",
                  "Yellow" = "#FEDB00",
                  "White" = "#FFFFFF"),  # St. Louis Cardinals
    cubs = c("Blue" = "#0E3386",
             "Red" = "#CC3433"),  # Chicago Cubs
    diamondbacks = c("Sedona Red" = "#A71930",
                     "Sonoran Sand" = "#E3D4AD",
                     "Black" = "#000000",
                     "Teal" = "#30CED8",
                     "White" = "#FFFFFF"),  # Arizona Diamondbacks
    dodgers = c("Dodger Blue" = "#005A9C",
                "Red" = "#EF3E42",
                "Silver" = "#A5ACAF"),  # Los Angeles Dodgers
    giants = c("Orange" = "#FD5A1E",
               "Black" = "#27251F",
               "Beige" = "#EFD19F",
               "Gold" = "#AE8F6F"),  # San Francisco Giants
    guardians = c("Navy Blue" = "#00385D",
                  "Red" = "#E50022",
                  "White" = "#FFFFFF"),  # Cleveland Guardians
    mariners = c("Navy Blue" = "#0C2C56",
                 "Northwest Green" = "#005C5C",
                 "Silver" = "#C4CED4",
                 "Red" = "#D50032"),  # Seattle Mariners
    marlins = c("Miami Blue" = "#00A3E0",
                "Caliente Red" = "#EF3340",
                "Slate Gray" = "#41748D",
                "Midnight Black" = "#000000"),  # Miami Marlins
    mets = c("Blue" = "#002D72",
             "Orange" = "#FF5910"),  # New York Mets
    nationals = c("Red" = "#AB0003",
                  "Navy Blue" = "#14225A",
                  "White" = "#FFFFFF"),  # Washington Nationals
    orioles = c("Orange" = "#DF4601",
                "Black" = "#000000"),  # Baltimore Orioles
    padres = c("Brown" = "#2F241D",
               "Gold" = "#FFC425"),  # San Diego Padres
    phillies = c("Red" = "#E81828",
                 "Blue" = "#002D72",
                 "White" = "#FFFFFF"),  # Philadelphia Phillies
    pirates = c("Black" = "#27251F",
                "Gold" = "#FDB827"),  # Pittsburgh Pirates
    rangers = c("Blue" = "#003278",
                "Red" = "#C0111F"),  # Texas Rangers
    rays = c("Navy Blue" = "#092C5C",
             "Columbia Blue" = "#8FBCE6",
             "Yellow" = "#F5D130",
             "White" = "#FFFFFF"),  # Tampa Bay Rays
    red_sox = c("Red" = "#BD3039",
                "Blue" = "#0C2340",
                "White" = "#FFFFFF"),  # Boston Red Sox
    reds = c("Red" = "#C6011F",
             "Black" = "#000000"),  # Cincinnati Reds
    rockies = c("Rockies Purple" = "#333366",
                "Silver" = "#C4CED4",
                "Midnight Black" = "#131413"),  # Colorado Rockies
    royals = c("Royal Blue" = "#004687",
               "Gold" = "#BD9B60"),  # Kansas City Royals
    tigers = c("Navy" = "#0C2340",
               "Orange" = "#FA4616"),  # Detroit Tigers
    twins = c("Twins Navy" = "#002B5C",
              "Scarlet Red" = "#D31145",
              "Kasota Gold" = "#B9975B"),  # Minnesota Twins
    white_sox = c("Black" = "#27251F",
                  "Silver" = "#C4CED4"),  # Chicago White Sox
    yankees = c("Blue" = "#003087",
                "Red" = "#E4002C",
                "Uniform Navy" = "#0C2340",
                "Uniform Gray" = "#C4CED3")  # New York Yankees
  ),

  nba = list(
    blazers = c("Red" = "#E03A3E",
                "Black" = "#000000"),  # Portland Trail Blazers
    bucks = c("Good Land Green" = "#00471B",
              "Cream City Cream" = "#EEE1C6",
              "Great Lakes Blue" = "#0077C0",
              "Black" = "#000000"),  # Milwaukee Bucks
    bulls = c("Bulls Red" = "#CE1141",
              "Black" = "#000000"),  # Chicago Bulls
    cavs = c("Cavaliers Wine" = "#860038",
             "Cavaliers Navy" = "#041E42",
             "Cavaliers Gold" = "#FDBB30",
             "Cavaliers Black" = "#000000"),  # Cleveland Cavaliers
    celtics = c("Celtics Green" = "#007A33",
                "Celtics Gold" = "#BA9653",
                "Celtics Brown" = "#963821",
                "White" = "#FFFFFF",
                "Celtics Black" = "#000000"),  # Boston Celtics
    clippers = c("Red" = "#C8102E",
                 "Blue" = "#1D428A",
                 "Silver" = "#BEC0C2",
                 "Black" = "#000000"),  # Los Angeles Clippers
    grizzlies = c("Blue" = "#5D76A9",
                  "Navy" = "#12173F",
                  "Yellow" = "#F5B112",
                  "Gray" = "#707271"),  # Memphis Grizzlies
    hawks = c("Torch Red" = "#C8102E",
              "Legacy Yellow" = "#FDB927",
              "Infinity Black" = "#000000",
              "Granite Gray" = "#9EA2A2",
              "White" = "#FFFFFF"),  # Atlanta Hawks
    heat = c("Red" = "#98002E",
             "Yellow" = "#F9A01B",
             "Black" = "#000000"),  # Miami Heat
    hornets = c("Hornets Purple" = "#1D1160",
                "Teal" = "#00788C",
                "Gray" = "#A1A1A4"),  # Charlotte Hornets
    jazz = c("Navy" = "#002B5C",
             "Green" = "#00471B",
             "Yellow" = "#F9A01B"),  # Utah Jazz
    kings = c("Purple" = "#5A2D81",
              "Gray" = "#63727A",
              "Black" = "#000000",
              "Kings Purple" = "#542E91",
              "Kings Grey" = "#C4CED4"),  # Sacramento Kings
    knicks = c("Knicks Blue" = "#006BB6",
               "Knicks Orange" = "#F58426",
               "Knicks Silver" = "#BEC0C2",
               "Knicks Black" = "#000000"),  # New York Knicks
    lakers = c("Lakers Purple" = "#552583",
               "Gold" = "#FDB927",
               "Black" = "#000000"),  # Los Angeles Lakers
    magic = c("Magic Blue" = "#0077C0",
              "Silver" = "#C4CED4",
              "Black" = "#000000"),  # Orlando Magic
    mavs = c("Royal Blue" = "#00538C",
             "Navy Blue" = "#002B5E",
             "Silver" = "#B8C4CA",
             "Black" = "#000000"),  # Dallas Mavericks
    nets = c("Black" = "#000000",
             "White" = "#FFFFFF"),  # Brooklyn Nets
    nuggets = c("Midnight Blue" = "#0E2240",
                "Sunshine Yellow" = "#FEC524",
                "Flatirons Red" = "#8B2131",
                "Skyline Blue" = "#1D428A"),  # Denver Nuggets
    pacers = c("Pacers Blue" = "#002D62",
               "Yellow" = "#FDBB30",
               "Silver" = "#BEC0C2"),  # Indiana Pacers
    pelicans = c("Pelicans Navy" = "#0C2340",
                 "Pelicans Red" = "#C8102E",
                 "Pelicans Gold" = "#85714D"),  # New Orleans Pelicans
    pistons = c("Red" = "#C8102E",
                "Royal" = "#1D42BA",
                "Gray" = "#BEC0C2",
                "Navy" = "#002D62"),  # Detroit Pistons
    raptors = c("Red" = "#CE1141",
                "Black" = "#000000",
                "Silver" = "#A1A1A4",
                "Gold" = "#B4975A"),  # Toronto Raptors
    rockets = c("Red" = "#CE1141",
                "Black" = "#000000",
                "Silver" = "#C4CED4"),  # Houston Rockets
    sixers = c("Blue" = "#006BB6",
               "Red" = "#ED174C",
               "Navy" = "#002B5C",
               "Silver" = "#C4CED4"),  # Philadelphia 76ers
    sonics = c("Green" = "#00653A",
               "Yellow" = "#FFC200",
               "White" = "#FFFFFF"),  # Seattle SuperSonics
    spurs = c("Silver" = "#C4CED4",
              "Black" = "#000000",
              "Silver" = "#8A8D8F",
              "Fuschia" = "#EF426F",
              "Blue" = "#00B2A9",
              "Orange" = "#FF8200"),  # San Antonio Spurs
    suns = c("Purple" = "#1D1160",
             "Orange" = "#E56020",
             "Black" = "#000000",
             "Gray" = "#63727A",
             "Yellow" = "#F9AD1B",
             "Dark Orange" = "#B95915",
             "Light Gray" = "#BEC0C2"),  # Phoenix Suns
    thunder = c("Thunder Blue" = "#007AC1",
                "Sunset" = "#EF3B24",
                "Blue" = "#002D62",
                "Yellow" = "#FDBB30"),  # Oklahoma City Thunder
    warriors = c("Warriors Blue" = "#1D428A",
                 "Golden Yellow" = "#FFC72C"),  # Golden State Warriors
    wizards = c("Navy Blue" = "#002B5C",
                "Red" = "#E31837",
                "Silver" = "#C4CED4"),  # Washington Wizards
    wolves = c("Midnight Blue" = "#0C2340",
               "Lake Blue" = "#236192",
               "Moonlight Grey" = "#9EA2A2",
               "Aurora Green" = "#78BE20")  # Minnesota Timberwolves
  ),

  wnba = list(
    aces = c("Red" = "#BA0C2F",
             "Black" = "#000000",
             "Gold" = "#85714D",
             "Silver" = "#8A8D8F"),  # Las Vegas Aces
    dream = c("Red" = "#C8102E",
              "Blue" = "#418FDE",
              "Light Blue" = "#CED9E5",
              "Navy" = "#0C2340"),  # Atlanta Dream
    fever = c("Red" = "#C8102E",
              "Blue" = "#041E42",
              "Yellow" = "#FFCD00"),  # Indiana Fever
    fire = c("Black" = "#000000",
             "Soft Black" = "#1B1B1B",
             "Red" = "#C8102E",
             "Pale Blue" = "#CEE5EB",
             "White" = "#FFFFFF"),  # Portland Fire
    liberty = c("Green" = "#6ECEB2",
                "Black" = "#000000",
                "Orange" = "#FF671F",
                "Blue" = "#003DA5"),  # New York Liberty
    lynx = c("Navy" = "#0C2340",
             "Blue" = "#236192",
             "Green" = "#78BE20",
             "Gray" = "#9EA2A2"),  # Minnesota Lynx
    mercury = c("Purple" = "#201747",
                "Orange" = "#CB6015",
                "Light Gray" = "#B1B3B3",
                "Black" = "#000000"),  # Phoenix Mercury
    mystics = c("Blue" = "#0C2340",
                "Red" = "#C8102E",
                "Silver" = "#8A8D8F"),  # Washington Mystics
    sky = c("Yellow" = "#FFCD00",
            "Blue" = "#418FDE"),  # Chicago Sky
    sparks = c("Yellow" = "#FFC72C",
               "Purple" = "#702F8A",
               "Green" = "#00B398",
               "Black" = "#000000"),  # Los Angeles Sparks
    storm = c("Yellow" = "#FBE122",
              "Green" = "#2C5234",
              "Gray" = "#A2AAAD"),  # Seattle Storm
    sun = c("Red" = "#A6192E",
            "Blue" = "#041E42",
            "Dark Red" = "#643335",
            "Orange" = "#DC4405",
            "Yellow" = "#FFC72C",
            "Light Yellow" = "#FFF0D8"),  # Connecticut Sun
    tempo = c("Bordeaux" = "#441E36",
              "Dark Bordeaux" = "#35182B",
              "Borealis Blue" = "#B3C7E7",
              "Black" = "#000000",
              "White" = "#FFFFFF"),  # Toronto Tempo
    valkyries = c("Valkyrie Violet" = "#B896D4",
                  "Light Violet" = "#C6ABDD",
                  "Black" = "#000000",
                  "Gold" = "#B9975B",
                  "White" = "#FFFFFF"),  # Golden State Valkyries
    wings = c("Navy" = "#0C2340",
              "Green" = "#C4D600",
              "Cyan" = "#00A9E0",
              "Blue" = "#0057B8",
              "Red" = "#C8102E")  # Dallas Wings
  ),

  nfl = list(
    bears = c("Dark Navy" = "#0B162A",
              "Orange" = "#C83803"),  # Chicago Bears
    bengals = c("Orange" = "#FB4F14",
                "Black" = "#000000"),  # Cincinnati Bengals
    bills = c("Blue" = "#00338D",
              "Red" = "#C60C30"),  # Buffalo Bills
    broncos = c("Broncos Orange" = "#FB4F14",
                "Broncos Navy" = "#002244"),  # Denver Broncos
    browns = c("Dark Brown" = "#311D00",
               "Orange" = "#FF3C00",
               "White" = "#FFFFFF",
               "Brown" = "#342624",
               "Orange" = "#EC5614",
               "Gray" = "#7C7E7C"),  # Cleveland Browns
    buccaneers = c("Red" = "#D50A0A",
                   "Bay Orange" = "#FF7900",
                   "Black" = "#0A0A08",
                   "Grey" = "#B1BABF",
                   "Pewter" = "#34302B"),  # Tampa Bay Buccaneers
    cardinals = c("Red" = "#97233F",
                  "Black" = "#000000",
                  "Yellow" = "#FFB612"),  # Arizona Cardinals
    chargers = c("Powder Blue" = "#0080C6",
                 "Sunshine Gold" = "#FFC20E",
                 "White" = "#FFFFFF"),  # Los Angeles Chargers
    chiefs = c("Red" = "#E31837",
               "Gold" = "#FFB81C"),  # Kansas City Chiefs
    colts = c("Speed Blue" = "#002C5F",
              "Gray" = "#A2AAAD"),  # Indianapolis Colts
    commanders = c("Burgundy" = "#5A1414",
                   "Gold" = "#FFB612"),  # Washington Commanders
    cowboys = c("Royal Blue" = "#003594",
                "Blue" = "#041E42",
                "Silver" = "#869397",
                "Silver-Green" = "#7F9695",
                "White" = "#FFFFFF"),  # Dallas Cowboys
    dolphins = c("Aqua" = "#008E97",
                 "Orange" = "#FC4C02",
                 "Blue" = "#005778"),  # Miami Dolphins
    eagles = c("Midnight Green" = "#004C54",
               "Silver (Jersey)" = "#A5ACAF",
               "Silver (Helmet)" = "#ACC0C6",
               "Black" = "#000000",
               "Charcoal" = "#565A5C"),  # Philadelphia Eagles
    falcons = c("Red" = "#A71930",
                "Silver" = "#A5ACAF"),  # Atlanta Falcons
    giants = c("Dark Blue" = "#0B2265",
               "Red" = "#A71930",
               "Gray" = "#A5ACAF"),  # New York Giants
    jaguars = c("Black" = "#101820",
                "Gold" = "#D7A22A",
                "Dark Gold" = "#9F792C",
                "Teal" = "#006778"),  # Jacksonville Jaguars
    jets = c("Gotham Green" = "#125740",
             "Stealth Black" = "#000000",
             "Spotlight White" = "#FFFFFF"),  # New York Jets
    lions = c("Honolulu Blue" = "#0076B6",
              "Silver" = "#B0B7BC",
              "Black" = "#000000",
              "White" = "#FFFFFF"),  # Detroit Lions
    niners = c("49ers Red" = "#AA0000",
               "Gold" = "#B3995D"),  # San Francisco 49ers
    packers = c("Dark Green" = "#203731",
                "Gold" = "#FFB612"),  # Green Bay Packers
    panthers = c("Carolina Blue" = "#0085CA",
                 "Black" = "#101820",
                 "Silver" = "#BFC0BF"),  # Carolina Panthers
    patriots = c("Nautical Blue" = "#002244",
                 "Red" = "#C60C30",
                 "New Century Silver" = "#B0B7BC"),  # New England Patriots
    raiders = c("Raiders Black" = "#000000",
                "Raiders Silver" = "#A5ACAF"),  # Las Vegas Raiders
    rams = c("Blue" = "#003594",
             "Gold" = "#FFA300",
             "Dark Gold" = "#FF8200",
             "Yellow" = "#FFD100",
             "White" = "#FFFFFF"),  # Los Angeles Rams
    ravens = c("Purple" = "#241773",
               "Black" = "#000000",
               "Metallic Gold" = "#9E7C0C",
               "Red" = "#C60C30"),  # Baltimore Ravens
    saints = c("Old Gold" = "#D3BC8D",
               "Black" = "#101820"),  # New Orleans Saints
    seahawks = c("College Navy" = "#002244",
                 "Action Green" = "#69BE28",
                 "Wolf Gray" = "#A5ACAF"),  # Seattle Seahawks
    steelers = c("Steelers Gold" = "#FFB612",
                 "Black" = "#101820",
                 "Blue" = "#003087",
                 "Red" = "#C60C30",
                 "Silver" = "#A5ACAF"),  # Pittsburgh Steelers
    texans = c("Deep Steel Blue" = "#03202F",
               "Battle Red" = "#A71930"),  # Houston Texans
    titans = c("Titans Navy" = "#0C2340",
               "Titans Blue" = "#4B92DB",
               "Titans Red" = "#C8102E",
               "Titans Silver" = "#8A8D8F",
               "Wolf Grey" = "#A2AAAD",
               "Steel Grey" = "#54585A"),  # Tennessee Titans
    vikings = c("Purple" = "#4F2683",
                "Gold" = "#FFC62F")  # Minnesota Vikings
  ),

  nhl = list(
    avalanche = c("Burgundy" = "#6F263D",
                  "Blue" = "#236192",
                  "Silver" = "#A2AAAD",
                  "Black" = "#000000"),  # Colorado Avalanche
    blackhawks = c("Red" = "#CF0A2C",
                   "Orange" = "#FF671B",
                   "Green" = "#00833E",
                   "Yellow" = "#FFD100",
                   "Tan" = "#D18A00",
                   "Blue" = "#001970",
                   "Black" = "#000000",
                   "White" = "#FFFFFF"),  # Chicago Blackhawks
    blue_jackets = c("Union Blue" = "#002654",
                     "Goal Red" = "#CE1126",
                     "Capital Silver" = "#A4A9AD"),  # Columbus Blue Jackets
    blues = c("Blue" = "#002F87",
              "Yellow" = "#FCB514",
              "Navy Blue" = "#041E42",
              "White" = "#FFFFFF"),  # St. Louis Blues
    bruins = c("Gold" = "#FFB81C",
               "Black" = "#000000"),  # Boston Bruins
    canadiens = c("Red" = "#AF1E2D",
                  "Blue" = "#192168"),  # Montreal Canadiens
    canucks = c("Blue" = "#00205B",
                "Green" = "#00843D",
                "Dark Blue" = "#041C2C",
                "Gray" = "#99999A",
                "White" = "#FFFFFF"),  # Vancouver Canucks
    capitals = c("Navy" = "#041E42",
                 "Red" = "#C8102E",
                 "White" = "#FFFFFF"),  # Washington Capitals
    coyotes = c("Brick Red" = "#8C2633",
                "Desert Sand" = "#E2D6B5",
                "Black" = "#111111"),  # Arizona Coyotes
    devils = c("Red" = "#CE1126",
               "Black" = "#000000",
               "White" = "#FFFFFF"),  # New Jersey Devils
    ducks = c("Orange" = "#F47A38",
              "Metallic Gold" = "#B9975B",
              "Silver" = "#C1C6C8",
              "Black" = "#000000",
              "Green" = "#00685E",
              "Purple" = "#532A44",
              "Yellow" = "#FCC72C",
              "Black" = "#241E24"),  # Anaheim Ducks
    flames = c("Red" = "#D2001C",
               "Yellow" = "#FAAF19",
               "White" = "#FFFFFF"),  # Calgary Flames
    flyers = c("Flyers Orange" = "#F74902",
               "Black" = "#000000",
               "White" = "#FFFFFF"),  # Philadelphia Flyers
    golden_knights = c("Gold" = "#B4975A",
                       "Steel Gray" = "#333F42",
                       "Red" = "#C8102E",
                       "Black" = "#000000",
                       "White" = "#FFFFFF"),  # Vegas Golden Knights
    hurricanes = c("Red" = "#CE1126",
                   "White" = "#FFFFFF",
                   "Gray" = "#A4A9AD",
                   "Black" = "#000000"),  # Carolina Hurricanes
    islanders = c("Blue" = "#00539B",
                  "Orange" = "#F47D30"),  # New York Islanders
    jets = c("Navy" = "#041E42",
             "Blue" = "#004C97",
             "Red" = "#AC162C",
             "Maroon" = "#7B303E",
             "Dark Gray" = "#55565A",
             "Silver" = "#8E9090",
             "White" = "#FFFFFF"),  # Winnipeg Jets
    kings = c("Black" = "#111111",
              "Silver" = "#A2AAAD",
              "White" = "#FFFFFF"),  # Los Angeles Kings
    kraken = c("Deep Sea Blue" = "#001628",
               "Ice Blue" = "#99D9D9",
               "Boundless Blue" = "#355464",
               "Shadow Blue" = "#68A2B9",
               "Red Alert" = "#E9072B"),  # Seattle Kraken
    lightning = c("Blue" = "#002868",
                  "White" = "#FFFFFF"),  # Tampa Bay Lightning
    maple_leafs = c("Blue" = "#00205B",
                    "White" = "#FFFFFF"),  # Toronto Maple Leafs
    oilers = c("Blue" = "#041E42",
               "Orange" = "#FF4C00"),  # Edmonton Oilers
    panthers = c("Navy" = "#041E42",
                 "Red" = "#C8102E",
                 "Tan" = "#B9975B"),  # Florida Panthers
    penguins = c("Black" = "#000000",
                 "Gold" = "#CFC493",
                 "Yellow" = "#FCB514",
                 "White" = "#FFFFFF"),  # Pittsburgh Penguins
    predators = c("Gold" = "#FFB81C",
                  "Navy Blue" = "#041E42",
                  "White" = "#FFFFFF"),  # Nashville Predators
    rangers = c("Blue" = "#0038A8",
                "Red" = "#CE1126",
                "White" = "#FFFFFF"),  # New York Rangers
    red_wings = c("Red" = "#CE1126",
                  "White" = "#FFFFFF"),  # Detroit Red Wings
    sabres = c("Royal Blue" = "#003087",
               "Gold" = "#FFB81C",
               "White" = "#FFFFFF"),  # Buffalo Sabres
    senators = c("Black" = "#000000",
                 "Red" = "#DA1A32",
                 "Gold" = "#B79257",
                 "White" = "#FFFFFF"),  # Ottawa Senators
    sharks = c("Teal" = "#006D75",
               "Orange" = "#EA7200",
               "Black" = "#000000",
               "White" = "#FFFFFF"),  # San Jose Sharks
    stars = c("Victory Green" = "#006847",
              "Silver" = "#8F8F8C",
              "Black" = "#111111"),  # Dallas Stars
    utah = c("Rock Black" = "#010101",
             "Salt White" = "#FFFFFF",
             "Mountain Blue" = "#7AB2E0"),  # Utah Mammoth
    wild = c("Iron Range Red" = "#A6192E",
             "Forest Green" = "#154734",
             "Gold" = "#EAAA00",
             "Minnesota Wheat" = "#DDCBA4")  # Minnesota Wild
  )
)
